version: "3.8"

volumes:
 certs:
   driver: local
 ollama:
    driver: local

networks:
 default_network:
      driver: bridge

services:
 ollama:
  image: ollama/ollama
  container_name: ollama
  volumes:
    - ollama:/root/.ollama
  ports:
    - "11434:11434"
  networks:
    - default_network

 streamlit:
  build: .
  container_name: streamlit
  ports:
    - "8501:8501"
  networks:
    - default_network
  depends_on:
    ollama:
        condition: service_started